version: '3.5'

services:
  server:
    image: ${CONSUL_IMAGE}
    container_name: server
    hostname: server
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: ${CONSUL_IMAGE}
    hostname: agent
    ports:
      - 5000:5000
      - 80:80
    container_name: agent
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: agent